### ISSUE TITLE
Issue with PDF output

### ISSUE THREAD

**Issue by oleteacher** [nabble/web2pdf#1]
I know is a is an old project, but just what needed for classroom project.

My bin and log folders are writable. Tried with old code and then tried with updated snappy. Below results are exact.

Issue is when using URL `http://local.dev/web2pdf/index.php?url=http%3A%2F%2Fwww.google.com&filename=google+homepage`. Removing `%3A%2F%2F` and relacing with `://` has no effect.

Above URL produces: 'google homepage.pdf' (actualy surrounded by '') and PDF is corrupt. No console errors so not sure how to proceed.

Hoping you may have a tip or two.

**Comment by hongaar** [comment]
@oleteacher I'm afraid I won't be able to help with this issue. It's been a long time since I used PHP. Could changes to the PHP runtime or dependencies be the issue? This probably ran on some version of PHP 5. Hope you can find a solution!

BTW do you need a PHP project? There must be similar projects, not sure about PHP ones though...

**Comment by oleteacher** [comment]
Thank you for reply @hongaar . I will have an associate that is better with PHP take a look at issue.

No errors thrown in PHP 7+ or PHP 8, so hard to tell if compatibility issue.

I have found no other projects like this one but will look around.

Thank you again for reply. WIll close this issue.

**Comment by hongaar** [comment]
@oleteacher I couldn't resist and pushed some changes which now work for me with the latest version of PHP. Make sure to follow the instructions in the updated README in order to install the new dependencies. If you still get an error, you can now append `&debug` to the URL to get some debugging information in the browser. Hope this helps!

**Comment by oleteacher** [comment]
Thank you @hongaar 

I tried a totally new composer setup on an almalinux 8 local dev server. The PDF was downloadable, but was corrupt:

![image](https://user-images.githubusercontent.com/26278259/217355944-6f28444a-d7e7-48f2-bfc0-f480acbfa1ca.png)

Adding on the debug tag got me on track. I would not have guessed it was this issue:

```
Fatal error:  Uncaught RuntimeException: The exit status code '126' says something went wrong:
stderr: "/www/wwwroot/mypdftest.local//web2pdf/vendor/bin/wkhtmltopdf-amd64: line 37: /www/wwwroot/mypdftest.local/web2pdf/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: Permission denied
```
Setting write on above and all worked perfectly.

Thanks much for taking time to help.

**Comment by hongaar** [comment]
@oleteacher glad it worked out!

Quick note that this is a very crude script and could have various security problems. Be careful and probably don't use it on an exposed server.
